### ISSUE TITLE
[Question] How to mark env variable as required?

### ISSUE THREAD

**Issue by dikkini** [ilyakaznacheev/cleanenv#46]
Hello!

Nice library. 

Is there avaiable to mark config parameter as required and get error if it is not set?

**Comment by ilyakaznacheev** [comment]
Thanks @dikkini 

No, this is not available at the moment because my idea was that the configuration structure or configuration file contains some default values that are overwritten in a given environment as needed.

Do you think it would be a useful feature?

**Comment by dikkini** [comment]
I'm afraid that without this feature it is not quite usefull library, because it is very important to know that config or env does not contain required variable and application wont work properly.

**Comment by ilyakaznacheev** [comment]
Hmm, okay, I'll think about the better way to implement this.

**Comment by dikkini** [comment]
I can help if u need this.

**Comment by ilyakaznacheev** [comment]
Yeah, sure, I'd appreciate it.

I see it as a tag that will return an error in case the field has a default value.

Since I don't want the tags to interfere with other libraries, I'd rather call it something like `` `env-required` `` or something like that. 

I don't think it makes sense to make it like `` `env: "NAME,required"` `` because we want to check not only environment variables but any data sources in general.

I think we could add a function like `validate(interface{}) error`, and call it at the end of `ReadConfig` and `ReadEnv` - after calling `readEnvVars`. Perhaps there will be other validations added in the future.

Or maybe it is better to do it in the function `parseENV' so as not to duplicate reflection - we read all the tags in this method anyway.

Anyway, I'm ready to discuss.

**Comment by dikkini** [comment]
```
type AppConfig struct {
	IsDebug       bool `env:"RE_IS_DEBUG" env-default:"true"`
	ElasticSearch struct {
		URLs     []string `env:"RE_ES_URLS" env-default:"http://localhost:9200"`
		Username string   `env:"RE_ES_USERNAME" env-required:"true"`
		Password string   `env:"RE_ES_PWD" env-required:"true"`
	}
	RuleCacheSize      int `env:"RE_RULE_CACHE_SIZE" env-default:"104857600" env-description:"In bytes, where 1024 * 1024 represents a single Megabyte, and 100 * 1024*1024 represents 100 Megabytes."`
}
```
my config from project.

`env-required` - seems legit.

---

add field `IsRequired` to `structMeta` to return metas than in block:

```golang
		for _, env := range meta.envList {
			if value, ok := os.LookupEnv(env); ok {
				rawValue = &value
				break
			}
		}
```
add one more if to check new field `IsRequired`:
```golang
`if meta.IsRequired (
  fmt.Sprintf("config variable %s is required",  env)
)
```

something like this.

**Comment by ilyakaznacheev** [comment]
Looks good. Except in our case, we have to return the error.

**Comment by dikkini** [comment]
> Looks good. Except in our case, we have to return the error.

I update my comment.

I miss validation for configuration file.

**Comment by s3rj1k** [comment]
+1 for this, this is basically the one singe thing that needs to be added to start using library.

**Comment by s3rj1k** [comment]
@dikkini @ilyakaznacheev Any updates on this?

**Comment by ilyakaznacheev** [comment]
@dikkini you can do that if you want. I think, for now, it will be enough to do the simplest solution with `env-required`.

I have some ideas with custom processors (so that people can expand the library with their own logic, like #47), and perhaps as part of that change, I will somehow refine the validation. 

But for now, the simplest option should be enough. So you can help to implement this feature if you want.

**Comment by ilyakaznacheev** [comment]
Otherwise, I'll try to add this feature this weekend, there's just not enough time right now.

**Comment by ilyakaznacheev** [comment]
Finally done :)
