### ISSUE TITLE
env-default bool value

### ISSUE THREAD

**Issue by baldator** [ilyakaznacheev/cleanenv#69]
Hi,

I'm experiencing a strange behavior and I'd like to understand if it's the expected behavior or a bug (in that case I can create a PR and fix it).
I do have a bool field in my config and the env-default value is true. If I define the field in my config file to false I would expect the value to be set to false, but I get true.

I looked in the code and the isZero function is considering false as zero (which makes sense in general but probably not in this case). 

Could you confirm what would be the expected behavior?
Thanks,
Marco

**Comment by ilyakaznacheev** [comment]
Hi Marco,

This is kinda expected behavior for now because there is no way to differentiate `false` as an empty/absent field and `false` as a field value after the file parsing process.

It is technically possible but requires to write own parser (for each supported format). And this is not what I want to do as a part of this library (and not as a part of my life). 

So unfortunately the only way, for now, to differentiate missing bool field and field with `false` is to use bool pointer type. It will be nil when the field is missing, and will point to false if the field is false.

Hope this will solve your problem.
