### ISSUE TITLE
Map of string to array of strings

### ISSUE THREAD

**Issue by azaz5959** [ilyakaznacheev/cleanenv#72]
How can we use map of string to array of strings in ENV?
Suppose we have :
`MapStringArrayString map[string][]string `env:"TEST_MAPSTRINGARRAYSTRING"``
Is it even possible with current implementation?

**Comment by ilyakaznacheev** [comment]
It is not supported by design, but you can do it now by means of some little tricks.

The library can parse nested structures from environment string variables, but parsing a map of string slices is a tricky one.
The library was designed to parse simple types (not nested), so there is nothing like dynamic parsing (like JSON, etc.), so the library tries to define the type of the variable and then parse the string data into the variable according to the type.

In the case of a map of string slices, there is no way (for now) to specify the string slice with brackets or something, because the library expects to parse either slice (comma-separated list of strings, like `a,b,c,d`) or map (comma-separated list of colon-separated key-value pairs, like `a:b,c:d`).

When you want to parse a map of string slices, it is difficult to understand when the slice ends and next key-value pair begins (again, because there are no brackets or something now). But you may do a trick and redefine the map separator with another symbol. The library then will use the symbol to split the map into key-value pairs, and then will try to parse each value into a string slice using a default separator - a comma.

`a:x,y;b:v,w`

[See an example](https://goplay.space/#z2I-6SV5d3P)
